### ISSUE TITLE
Implement discovery endpoints

### ISSUE THREAD

**Issue by reyraa** [Muzikie/streamer-archived#17]
Streamer should enable the player applications to access indexed data of the blockchain. Meaning, it should expose expose endpoints to store values and returned the list of entities. We'll replace this functionality with Lisk Service once it's stable enough.
Therefore the following endpoints are required:
- Collection
  - getAll
    - Method: `GET`
    - Params: `limit`, `offset`.
    - Description: List of all collections in the system including the details of their Audios.
  - getByAddress
    - Method: `GET`
    - Params: `address`, `limit`, `offset`.
    - Description: List of all collections of a given account including the details of their Audios.
- Subscription
  - getTypes
    - Method: `GET`
    - Params: none.
    - Description: List of all subscriptions types and 10 available IDs for each type

**Comment by haghighatcs** [comment]
Resolved by #37
